[package]
name = "si2mqtt"
version = "0.1.0"
authors = ["Simon Cocking <simon@cocking.id.au>"]

[dependencies]
mosquitto-client = "0.1.4"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
regex = "0.2"